apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web
spec:
  replicas: 1
  selector:
    matchLabels: { app: php-web }
  template:
    metadata:
      labels: { app: php-web }
    spec:
      securityContext:
        fsGroup: 1001   # usuário/grupo padrão da imagem bitnami
      initContainers:
        - name: bootstrap-content
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -e
              if [ ! -f /app/index.php ]; then
                cp /bootstrap/index.php /app/index.php
                chown 1001:1001 /app/index.php
              fi
          volumeMounts:
            - name: php-content
              mountPath: /app
            - name: php-bootstrap
              mountPath: /bootstrap
      containers:
        - name: php-apache
          image: bitnami/php-apache:8.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: php-content
              mountPath: /app
      volumes:
        - name: php-content
          persistentVolumeClaim:
            claimName: php-content
        - name: php-bootstrap
          configMap:
            name: php-bootstrap
            items:
              - key: index.php
                path: index.php
