apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joget-dx8-tomcat9-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # increase the ingress timeout to avoid "ERROR: Gateway Time-out" during Joget DX8 Initial Database Setup
    nginx.ingress.kubernetes.io/app-root: /jw
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"  
    # increase size limit for attachments in Joget
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"  
spec:
  ingressClassName: nginx
  rules:
    - host: joget8.lan
      http:
        paths:
          - path: /jw
            pathType: Prefix
            backend:
              service:
                name: joget-dx8-tomcat9
                port:
                  number: 8080
